lib/personalfin_web/router.ex
defmodule PersonalfinWeb.Router do
  use PersonalfinWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PersonalfinWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PersonalfinWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/compare", PersonalfinWeb.Compare, as: :compare do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/expenses", PersonalfinWeb.Expense, as: :expense do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/management", PersonalfinWeb.Management, as: :management do
    pipe_through :browser

    get "/", PageController, :index
    get "/accounts/connect/:bank", AccountController, :connect
    get "/accounts/connected", AccountController, :connected
    resources "/accounts", AccountController, except: [:show]
    resources "/investments", InvestmentController, except: [:show]
    resources "/stocks", StockController, except: [:show]
    get "/transactions", TransactionController, :index
    post "/transactions/update_categories", TransactionController, :update_categories
    post "/transactions/update_transactions", TransactionController, :update_transactions
  end

  scope "/projection", PersonalfinWeb.Projection, as: :projection do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", PersonalfinWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: PersonalfinWeb.Telemetry
    end
  end
end

lib/personalfin_web/views/layout_view.ex
defmodule PersonalfinWeb.LayoutView do
  use PersonalfinWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/personalfin_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/personalfin_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/personalfin_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="csrf-token" content={csrf_token_value()}>
  <%= live_title_tag assigns[:page_title] || "Personalfin", suffix: " · Phoenix Framework" %>
  <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>

  <script phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  <script src="//www.google.com/jsapi"></script>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <%= link "Home", to: Routes.page_path(@conn, :index), class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Management
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <li><%= link "Overview", to: Routes.management_page_path(@conn, :index), class: "dropdown-item"%></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link "Accounts", to: Routes.management_account_path(@conn, :index), class: "dropdown-item" %></li>
            <li><%= link "Investments", to: Routes.management_investment_path(@conn, :index), class: "dropdown-item" %></li>
            <li><%= link "Stocks", to: Routes.management_stock_path(@conn, :index), class: "dropdown-item" %></li>
            <li><%= link "Transactions", to: Routes.management_transaction_path(@conn, :index), class: "dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link "Projection", to: Routes.projection_page_path(@conn, :index), class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link "Compare", to: Routes.compare_page_path(@conn, :index), class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link "Expenses", to: Routes.expense_page_path(@conn, :index), class: "nav-link"%>
        </li>
      </ul>
      <ul class="navbar-nav">
        <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
        <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home), class: "nav-link" %></li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

<main role="main" class="container" style="margin-top: 75px">
  <%= @inner_content %>
</main>

</body>
</html>